sudo: required
dist: trusty
language: python
python: 2.7
env:
    - TOXENV=py27
install: pip install tox
script: tox
cache:
    directories:
        - .tox
        - $HOME/.cache/pip
before_install:
    - echo "deb http://http.debian.net/debian jessie-backports main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -y
    - sudo apt-get install libgrpc-dev -y --force-yes
    - pip install grpcio protobuf
